sets:
  - selector:
      files:
        - AGENTS.md
        - .xdrs/_core/**
      exclude:
        - "**/*.test.js"
        - "**/*.test.int.js"
        - "**/*.test.int.report"
    output:
      path: .
      symlinks:
        - source: .xdrs/**/skills/001-review
          target: .agents/skills
        - source: .xdrs/**/skills/008-write-xdrs-doc
          target: .agents/skills
      gitignore: false

  - selector:
      files:
        - .xdrs/index.md
    output:
      path: .
      gitignore: false
      managed: false
